"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Download, FileText, Loader2 } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { GENERATED_REPORTS, REPORT_DEFINITIONS } from "@/data/mock-reports";
import { formatDateTime } from "@/lib/utils";

export default function ReportsPage() {
  const [generatingId, setGeneratingId] = useState<string | null>(null);

  function handleGenerate(title: string, id: string) {
    setGeneratingId(id);
    toast.promise(new Promise((resolve) => setTimeout(resolve, 1600)), {
      loading: `Generating ${title}…`,
      success: `${title} generated successfully.`,
      error: `Failed to generate ${title}.`,
    });
    setTimeout(() => setGeneratingId(null), 1600);
  }

  return (
    <div className="flex flex-col pb-8">
      <PageHeader title="Reports" subtitle="Scheduled and on-demand security and compliance reporting" />

      <div className="grid grid-cols-1 gap-3 px-6 sm:grid-cols-2">
        {REPORT_DEFINITIONS.map((report) => (
          <Card key={report.id} className="flex flex-col p-4">
            <div className="flex items-start justify-between gap-3">
              <div className="flex items-start gap-3">
                <div className="flex size-9 shrink-0 items-center justify-center rounded-md bg-accent-soft">
                  <FileText className="size-4 text-accent-strong" />
                </div>
                <div>
                  <p className="text-[13.5px] font-semibold text-foreground">{report.title}</p>
                  <p className="mt-0.5 text-[12px] text-foreground-muted">{report.description}</p>
                </div>
              </div>
              <Badge variant="outline">{report.cadence}</Badge>
            </div>
            <div className="mt-3 flex items-center justify-between border-t border-border pt-3">
              <p className="text-[11.5px] text-foreground-faint">Last generated {formatDateTime(report.lastGeneratedAt)}</p>
              <Button
                size="sm"
                variant="secondary"
                disabled={generatingId === report.id}
                onClick={() => handleGenerate(report.title, report.id)}
              >
                {generatingId === report.id ? <Loader2 className="size-3.5 animate-spin" /> : null}
                Generate Report
              </Button>
            </div>
          </Card>
        ))}
      </div>

      <div className="px-6 pt-4">
        <Card className="overflow-hidden">
          <CardHeader className="border-b border-border pb-3">
            <CardTitle className="text-[14px]">Generated Reports</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead>Format</TableHead>
                  <TableHead className="text-right">Export</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {GENERATED_REPORTS.map((r) => (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium text-foreground">{r.title}</TableCell>
                    <TableCell className="text-[12.5px] text-foreground-muted">{r.period}</TableCell>
                    <TableCell className="text-[12.5px] text-foreground-muted">{r.generatedBy}</TableCell>
                    <TableCell className="text-[12.5px] text-foreground-muted">{formatDateTime(r.generatedAt)}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{r.format}</Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => toast.message(`Preparing ${r.format} export…`, { description: r.title })}
                      >
                        <Download className="size-3.5" /> {r.format}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
